---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _data
  label: Members
  create: documents
  match: "**/*"
  new_doc_ext: yml
  templates:
  - members
- type: directory
  path: _notes
  label: Notes
  create: documents
  match: "**/*"
  templates:
  - general
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - general
- type: jekyll-posts
  label: Research Projects
  create: documents
  templates:
  - research-projects
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
